### ISSUE TITLE
marker

### ISSUE THREAD

**Issue by nicispro** [rajan88lal88/geoguesser_clone#1]
how to add marker view like when i click choose location marker is disable

**Comment by rajan88lal88** [comment]
You want to remove the marker when "Choose location" is clicked?

**Comment by nicispro** [comment]
![image](https://user-images.githubusercontent.com/71666338/161779819-8ea6c328-ac7c-44c0-871c-fd68384a062b.png)
see i dont have marker

**Comment by nicispro** [comment]
How to fix that?

**Comment by rajan88lal88** [comment]
Updated the code
